version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clothes_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - clothes

  nginx:
    image: nginx:alpine
    container_name: clothes_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - clothes

  db:
    image: mysql:8
    container_name: clothes_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: clothes
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: clothes
    ports:
      - "3307:3306"
    networks:
      - clothes

networks:
  clothes:
